---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Academic and Professional Experience


## Education Background:


Columbia University   09/2020-05/2022     
Major: Biotechnology   
Expected Degree: Master of Art (2022.05)


Rutgers University-New Brunswick  09/2018-05/2020     
Major: Plant Biology   
Degree: Bachelor of Science 


Nanjing Agricultural University 09/2016-07/2018     
Major: Agro-grassland Science   
Degree: Bachelor of Science 


## Extracurricular Activities:                                               
09/2016-07/2018 
Activities Department of College’s Students Union                     
●	Planned and organized more than 30 arts performance and sports campus activities
●	Organized the university’s large-size speech competition

07/2018-08/2018 
Inner Mongolia Ecological Governance Team                           
●	Received training on collecting and making desert plants specimen and plants seeds
●	Visited and worked with the local citizens in the desert and the workers of the Desert Governance Station on planting drought resistant crop
●	Communicated with researchers in Desert Governance Station about desert governance objectives and plans
●	Wrote a research report on Status and Reasons of Desertification in Alashan Area and its Ecological Governance, together with my 4 team members  


## Research Experience:                                               
09/2019-11/2019 
Multiple Microorganisms’ influence on Seedling Ryegrass’ Growth in Optimum Conditions

●	Independently took charge of this research program
●	Cultured five kinds of rhizobacteria in Burkholderia sp and one in Burkholderia glathei
●	Cultivated ryegrass seedling by seed tissue culture
●	Measured the length, surface area, diameter, volume and biomass of root
●	Measured the biomass of shoot
    
05/2019-07/2019 
Multiple Microorganisms’ influence on Ryegrass’ Growth in a Drought Stress Environment

●	Independently took charge of this research program
●	Cultured five kinds of rhizobacteria in Burkholderia sp.
●	Sowed the seeds of ryegrass
●	Used two different methods (seed inoculation and soil drench inoculation) to apply rhizobacteria 
●	Measured the length, surface area, diameter, volume and biomass of root
●	Measured the biomass of shoot

03/2018-04/2019 Research of Melatonin’s Influence on Drought Resistance in Alfalfa   

●	Searched for relevant literature, through which I analyzed this research program’s feasibility
●	Assisted plants-seedling culture and inputting external melatonin to the plants
●	Assisted my professor in controlling plants’ moisture in weighing method and leading to plants’ drought stress 
●	Measured the plant height, stem diameter, quantity of primary branches
●	Learned to measure the SOD, CAT, POD enzyme activity which reflects the drought resistance in Alfalfa
●	Performed statistical analysis on experimental data 


## Internship Experience:                                                   
01/2019-01/2019 Guangxi Medicinal Botanical Garden          

●	Was mainly responsible for dandelion seeds cultivation job
●	involved in all the procedures of dandelion seeds cultivation operations

01/2021-05/2021 Blackstone Life Science                      

●	Generated a professional overview about gene editing technology
●	Evaluated and identified the best clinical trial stage gene editing therapies for investment
●	Estimated pre-clinical trial gene editing therapies that hold the most potential for investment

05/2021-07/2021 PuraPharm    

●	Researched the best conservation environmental conditions for natural products produced from herbal sources
●	Researched pretreated and extracted methods’ influence on natural products produced from herbal sources
●	Measured active ingredients of natural product from different extract methods with liquid chromatography





here's back to the [Home](index.html) page